### ISSUE TITLE
Clone -> build -> run has errors

### ISSUE THREAD

**Issue by liammclennan** [getgauge/gauge-example-csharp#2]
Built fine with VS2013, but run with `gauge specs/` produces:

```
Building Project: C:\temp\gauge\gauge-example-csharp\Gauge.Example.sln
Success

Unhandled Exception: System.TypeLoadException: Could not load type 'Gauge.CSharp.Lib.IScreenGrabber' from assembly 'Gauge.CSharp.Lib, Version=0.0.5.0, Culture=neutral, PublicKeyToken=null'.
   at Gauge.CSharp.Runner.Sandbox.<LoadAssemblyFiles>b__c(Type t)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Gauge.CSharp.Runner.Sandbox.<LoadAssemblyFiles>b__b(Type type) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\Sandbox.cs:line 119
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Gauge.CSharp.Runner.Sandbox.LoadAssemblyFiles() in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\Sandbox.cs:line 117
   at Gauge.CSharp.Runner.Sandbox.LoadAssemblyFiles()
   at Gauge.CSharp.Runner.SandboxFactory.Create(AppDomainSetup setup) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\SandboxFactory.cs:line 41
   at Gauge.CSharp.Runner.StartPhaseExecutor..ctor() in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\StartPhaseExecutor.cs:line 60
   at Gauge.CSharp.Runner.StartPhaseExecutor.GetDefaultInstance() in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\StartPhaseExecutor.cs:line 42
   at Gauge.CSharp.Runner.PhaseExecutorFactory.GetExecutor(String phase) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\PhaseExecutorFactory.cs:line 27
   at Gauge.CSharp.Runner.Program.Main(String[] args) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\Program.cs:line 49
16:02:42.577 [CRIT] Failed to start gauge API. Runner exited with error: exit status 255
```

**Comment by sriv** [comment]
The example seems to be out of date in dependencies. The Gauge.CSharp.Lib v.0.0.5.0 does not have `IScreenGrabber` defined. It came out later.

Will fix the example. But the runner shouldn't crash because it didn't find the type. So this would be a Gauge-CSharp issue : getgauge/gauge-csharp#31.

**Comment by sriv** [comment]
Should work now, the dependencies are updated to use the latest references. Please try updating your `gauge` and `gauge-csharp` installations as well.
